jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Startup
        uses: actions/checkout@v2
      - name: Pull Tools
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Tests
        run: ./main/action

name: Test

on:
  schedule:
    - cron: "20 0/3 * * *"
